Add hack to compile rhsm.certificate on login
candlepin/ansible-role-subman-devel pull request #3
Opened 2018-08-24 15:45 UTC by kahowell

2018-08-27 15:11 UTC, jirihnidek requested changes
This could work, but could expect automatic rebuilding od certificate.so, when source code is changed.

2018-08-27 15:11 UTC, jirihnidek commented on tasks/main.yml
> +    line: "test -f {{ subman_checkout_dir }}/src/rhsm/*certificate*.so || (cd {{ subman_checkout_dir}}; {{ subman_python_interpreter }} setup.py build_ext --inplace 2>&1 > /dev/null)"
When source code (`certificate.c`) is newer then target file `*certificate.so`, then it is also necessary to compile this file.

2018-09-21 14:46 UTC, kahowell commented
d71c555..accaf6b: change hack to use mtime.

@jirihnidek does this work for you?

2018-09-27 12:50 UTC, jirihnidek approved these changes
ACK

2018-09-27 12:50 UTC, merged